- include: prerequisites.yml

# @TODO: need to block untill service is up
- name: docker gluster
  hosts: gluster
  tasks:
  - name: start container
    docker:
      name: gluster
      state: reloaded
      image: million12/gluster
      privileged: true
      net: host
      devices:
      - /dev/fuse
      volumes:
      - /opt/gluster/volumes:/gluster
      - /opt/gluster/conf:/var/lib/glusterd
      env:
        TERM: xterm-256color
        TZ: Asia/Bangkok
  - wait_for: port=24007 delay=3

# Loop over gluster nodes, add them to peers and add-brick to volume
- name: docker gluster (master)
  hosts: gluster-master
  tasks:
  - name: configure master node
    script: >
      scripts/gluster_configure_master.sh \
        {{ hostvars[inventory_hostname]['ansible_enp0s3']['ipv4']['address'] }} \
        {{ hostvars[item]['ansible_enp0s3']['ipv4']['address'] }}
    with_items:
      - "{{ groups['gluster-nodes'] }}"

# mount volume on all nodes
#- name: mount gluster volume
  #hosts: gluster
  #tasks:
  #- name: mount gluster volume
    #script: scripts/gluster_mount_volume.sh
