- include: python+docker.yml

- name: prerequisites
  hosts: all
  tasks:
  - name: pip
    package: name=python-pip state=present use=auto
  - name: docker-py
    pip: name=docker-py version=1.8.1 state=present

